version: '3'

networks:
  openvpnacs_development-network:
    external: true
    driver: macvlan
    driver_opts:
      parent: "ens192"
    ipam:
      config:
        - subnet: 10.0.18.0/24
          gateway: 10.0.18.1

services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      openvpnacs_development-network:
         ipv4_address: 10.0.18.22

  dnsmasq:
    build: dnsmasq/.
    image: dnsmasq
    container_name: dnsmasq-proxy
    restart: always
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
      - ./dnsmasq/proxy.conf:/etc/dnsmasq.d/proxy.conf  
    networks:
      openvpnacs_development-network:
        ipv4_address: 10.0.18.23
